# Generated by Django 5.0.6 on 2024-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.TextField(default='https://i.pinimg.com/736x/4c/d2/a6/4cd2a6615820a4a15f4d85de7762251d.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
