# Generated by Django 5.0.6 on 2025-01-07 07:58

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.IntegerField(default=Auth.models.CustomUser.generate_verification_code),
        ),
    ]
