# Generated by Django 5.0.6 on 2024-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_playlists_delete_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='songs',
            field=models.TextField(default=''),
        ),
    ]
