# Generated by Django 5.0.6 on 2024-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_playlists_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='songs',
            field=models.TextField(blank=True),
        ),
    ]
