# Generated by Django 5.0.6 on 2024-12-07 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 15, 34, 34, 415753)),
        ),
    ]
