# Generated by Django 5.0.6 on 2024-12-03 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 19, 11, 24, 909930)),
        ),
    ]
