# Generated by Django 5.0.6 on 2024-12-03 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chatroom_online_count_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online_users',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 19, 55, 43, 446069)),
        ),
    ]
