# Generated by Django 5.0.6 on 2024-12-03 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_chatroom_online_users_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='online_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 19, 56, 41, 583059)),
        ),
    ]
