# Generated by Django 5.0.6 on 2024-12-15 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_chatroom_category_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allowed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 12, 1, 717187)),
        ),
    ]
