# Generated by Django 5.0.6 on 2025-01-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_alter_chatroommessages_created_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessages',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 18, 16, 43, 640853)),
        ),
    ]
