# Generated by Django 5.0.6 on 2025-01-07 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_chatroommessages_isdeleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 13, 1, 25, 235069)),
        ),
    ]
