# Generated by Django 5.0.6 on 2025-01-07 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 13, 45, 45, 139905)),
        ),
    ]
