# Generated by Django 5.0.6 on 2025-01-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 22, 16, 51, 860329)),
        ),
    ]
