# Generated by Django 5.1.5 on 2025-01-23 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0017_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
