# Generated by Django 5.0.6 on 2025-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0018_alter_chatroommessages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
