# Generated by Django 5.1.5 on 2025-02-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0019_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessages',
            name='filteredMessage',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='chatroommessages',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
