# Generated by Django 5.1.5 on 2025-02-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0020_chatroommessages_filteredmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessages',
            name='filteredMessage',
            field=models.TextField(blank=True),
        ),
    ]
