# Generated by Django 5.1.5 on 2025-02-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0021_alter_chatroommessages_filteredmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroommessages',
            old_name='filteredMessage',
            new_name='filteredWords',
        ),
    ]
